/* eslint-disable no-console */
// ATTN: setupTests.js is called by convention for the create-react-app
// https://facebook.github.io/create-react-app/docs/running-tests#initializing-test-environment
import firebaseMock from "firebase-mock";
import "react-testing-library/cleanup-after-each";

// jest/jsdom throws a not implemented exception for this
// instead, we just stub it out
global.scrollTo = jest.fn();

jest.doMock("firebaseFactory", () => {
  const mockAuth = new firebaseMock.MockAuthentication();
  const mockFirestore = new firebaseMock.MockFirestore();
  const mockSdk = new firebaseMock.MockFirebaseSdk(
    null, // RTDB
    () => mockAuth,
    () => mockFirestore
  );
  const firebase = mockSdk.initializeApp();
  firebase.auth().autoFlush(true);
  firebase.firestore().autoFlush(true);
  return { db: firebase.firestore(), firebase };
});

// IMPORTANT
// Below is a temporary hack to suppress warnings generated by a React bug.
// Source: https://github.com/testing-library/react-testing-library/issues/281
// @todo: remove this when React 16.9.0 is stable and we upgrade.
const originalError = console.error;
beforeAll(() => {
  console.error = (...args) => {
    if (/Warning.*not wrapped in act/.test(args[0])) {
      return;
    }
    originalError.call(console, ...args);
  };
});

afterAll(() => {
  console.error = originalError;
});
